<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ChordBLL\ChordBLL.csproj" />
    <ProjectReference Include="..\..\ChordCommon\ChordCommon.csproj" />
    <ProjectReference Include="..\..\ChordDAL\ChordDAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ChordBLL">
      <HintPath>..\..\ChordBLL\bin\Debug\net8.0\ChordBLL.dll</HintPath>
    </Reference>
    <Reference Include="ChordCommon">
      <HintPath>..\..\ChordBLL\bin\Debug\net8.0\ChordCommon.dll</HintPath>
    </Reference>
    <Reference Include="ChordDAL">
      <HintPath>..\..\ChordBLL\bin\Debug\net8.0\ChordDAL.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
